### ISSUE TITLE
NID 2022 Sem 4

### ISSUE THREAD

**Issue by pkd2512** [pkd2512/codeschool-webdev#1]
Hope y'all are having fun with code. 
* Any queries or problems you may face, put them in the comments here. 
* Drop in the links to your live websites!

Update: [Links to student scrolly maps](https://docs.google.com/spreadsheets/d/1XpDsf4xKx5z3Tom1wY9jvoi-jUwE2mpXXucuEDzbRds/edit#gid=0) from [Schematic Hometown Mapping assignment](https://github.com/mapschool/course/issues/65)

**Comment by JiteshChowdhury** [comment]
Guy's please feel free to send in your issues.

Seperately, adding few ai2html examples:
- https://graphics.reuters.com/HEALTH-CORONAVIRUS/EVOLUTION/yxmpjqkdzvr/
- https://graphics.reuters.com/CLIMATE-CHANGE/PERMAFROST/oakveelglvr/index.html
- https://graphics.reuters.com/HEALTH-CORONAVIRUS/SOCIALDISTANCING/qzjvqenmyvx/

Some of bit ambitious scrolly:
- https://graphics.reuters.com/MOVIES-GODFATHER/lbpgnmrynvq/index.html
- https://graphics.reuters.com/SPACE-EXPLORATION/TELESCOPE/klvyknwbrvg/index.html

**Comment by ginaphil** [comment]
live website : https://ginaphil.github.io/map-scroll/

issues : 1st image of the scroll is coming in between all the images for a small time frame
             how to hide annotation only for  just one image
             in deployment the images are not appearing but is working locally

pending updates : style changes to annotation

**Comment by kirtivardhanrathore** [comment]
I am also facing the same issue as Jeena. The console in live is showing the following error. The code is working fine in local host. 
<img width="898" alt="Error in Console" src="https://user-images.githubusercontent.com/93124181/160188480-ba2dedcc-03d0-40f5-a239-5ec8fa8d1455.png">

**Comment by pkd2512** [comment]
> live website : [ginaphil.github.io/map-scroll](https://ginaphil.github.io/map-scroll/)
> 
> issues : 1st image of the scroll is coming in between all the images for a small time frame how to hide annotation only for just one image in deployment the images are not appearing but is working locally
> 
> pending updates : style changes to annotation

@ginaphil

For hiding anno, use "\_blank-slide\_" in the anno text. I pushed some changes earlier to the files, so if it doesn't work, download the scrolly folder again from the scrolly branch.

Not sure what the first issue means, but if it gets fixed by itself, let's deal with it later. 

Re: deployment issue, I am running down that bug on my end. For now, keep perfecting things locally.

**Comment by pkd2512** [comment]
> I am also facing the same issue as Jeena. The console in live is showing the following error. The code is working fine in local host. <img alt="Error in Console" width="898" src="https://user-images.githubusercontent.com/93124181/160188480-ba2dedcc-03d0-40f5-a239-5ec8fa8d1455.png">

This issue should be fixed now. @kirtivardhanrathore

### Download the scrolly ejs and js files again from this repo and replace in your code.
Also, note that the js file name has changed, so import it accordingly in your app.js

**Comment by kirtivardhanrathore** [comment]
Thank You! It's working fine now! :')

**Comment by ginaphil** [comment]
Thankyou. Its working now. I will update with some style changes soon

**Comment by chickensoup28** [comment]
Hello, I have deployed my code and put it up on the spreadsheet. For some reason the images are now left aligned. Was working fine before I deployed the code though :disappointed_relieved:
![Screenshot 2022-03-28 122635](https://user-images.githubusercontent.com/93116394/160342931-8289da85-6108-41a5-8370-1f710e7e31e0.png)
![Screenshot 2022-03-28 122703](https://user-images.githubusercontent.com/93116394/160342952-e1970119-8800-4c28-8ad9-ae058ebe59c4.png)

Link to the live site : https://chickensoup28.github.io/infoviz_cartoz-setup/

**Comment by pkd2512** [comment]
> Hello, I have deployed my code and put it up on the spreadsheet. For some reason the images are now left aligned. Was working fine before I deployed the code though 😥 ![Screenshot 2022-03-28 122635](https://user-images.githubusercontent.com/93116394/160342931-8289da85-6108-41a5-8370-1f710e7e31e0.png) ![Screenshot 2022-03-28 122703](https://user-images.githubusercontent.com/93116394/160342952-e1970119-8800-4c28-8ad9-ae058ebe59c4.png)
> 
> Link to the live site : [chickensoup28.github.io/infoviz_cartoz-setup](https://chickensoup28.github.io/infoviz_cartoz-setup/)



@chickensoup28 Can you check if the `responsiveness: dynamic` is set in your ai2html settings? If not, try changing that.

Download the scrolly code from my repo again (I added some tweaks). Also, can you put the scrolly in a separate section and not inside a container. Check out my code for more references on the structure.

I see your page is missing the responsiveness meta tag in the head. Check the Bootstrap docs in my notes that tell you about the meta tag `<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by chickensoup28** [comment]
@pkd2512 Hey, I changed everything that you suggested. The live site works fine now, but the deployment page shows status as failure. 
![Screenshot 2022-03-29 003044](https://user-images.githubusercontent.com/93116394/160468760-d49e168a-d5d5-4637-86a6-efd897cc57a4.png)

Link to site- https://chickensoup28.github.io/infoviz_cartoz-setup/

**Comment by pkd2512** [comment]
> @pkd2512 Hey, I changed everything that you suggested. The live site works fine now, but the deployment page shows status as failure. ![Screenshot 2022-03-29 003044](https://user-images.githubusercontent.com/93116394/160468760-d49e168a-d5d5-4637-86a6-efd897cc57a4.png)
> 
> Link to site- [chickensoup28.github.io/infoviz_cartoz-setup](https://chickensoup28.github.io/infoviz_cartoz-setup/)

@chickensoup28

Interesting. Do the changes show up on the live page? Not sure what could go wrong. Did you try googling - github pages deployment error?

Also, make sure in the pages settings, it's pointing to the correct branch and folder

**Comment by chickensoup28** [comment]
> github pages deployment error
Hey, the changes do show up in the page. I tried googling to understand what went wrong, Here is something I found https://github.community/t/failure-deployed-on-github-pages/220671/8 (I couldn't follow this though :P, all I understood was that they were asking to delete a submodule.) 
Yes, the page setting is pointing to the correct branch and folder.

**Comment by pkd2512** [comment]
> > github pages deployment error
> > Hey, the changes do show up in the page. I tried googling to understand what went wrong, Here is something I found [github.community/t/failure-deployed-on-github-pages/220671/8](https://github.community/t/failure-deployed-on-github-pages/220671/8) (I couldn't follow this though :P, all I understood was that they were asking to delete a submodule.)
> > Yes, the page setting is pointing to the correct branch and folder.


@chickensoup28 
One thing you could try is to go to the Actions tab and check the last run deployment logs to see what went wrong. Or we could take a look sometime later.
